2025-01-10 12:03:42,890 - pathway_engine.engine.dataflow - INFO - Preparing Pathway computation
2025-01-10 12:11:12,707 - pathway_engine.engine.dataflow - INFO - Preparing Pathway computation
2025-01-10 12:11:15,442 - sentence_transformers.SentenceTransformer - INFO - Load pretrained SentenceTransformer: intfloat/e5-large-v2
2025-01-10 21:12:00,575 - sentence_transformers.SentenceTransformer - INFO - Load pretrained SentenceTransformer: intfloat/e5-large-v2
2025-01-10 21:22:25,557 - sentence_transformers.SentenceTransformer - INFO - Load pretrained SentenceTransformer: intfloat/e5-large-v2
2025-01-10 21:24:54,888 - sentence_transformers.SentenceTransformer - INFO - Load pretrained SentenceTransformer: intfloat/e5-large-v2
2025-01-10 21:25:04,559 - py.warnings - WARNING - /home/destroy0p/AgnijBiswas/Publishability-of-Research/venv/lib/python3.12/site-packages/pathway/xpacks/llm/vector_store.py:218: UserWarning: `_metadata` column is not present in Table <pathway.Table schema={'data': typing.Any}>. Filtering will not work for this Table
  warnings.warn(

2025-01-10 21:25:04,632 - py.warnings - WARNING - /home/destroy0p/AgnijBiswas/Publishability-of-Research/venv/lib/python3.12/site-packages/beartype/_util/hint/pep/utilpeptest.py:311: BeartypeDecorHintPep585DeprecationWarning: PEP 484 type hint typing.Sequence[str] deprecated by PEP 585. This hint is scheduled for removal in the first Python version released after October 5th, 2025. To resolve this, import this hint from "beartype.typing" rather than "typing". For further commentary and alternatives, see also:
    https://beartype.readthedocs.io/en/latest/api_roar/#pep-585-deprecations
  warn(

2025-01-10 21:25:05,052 - pathway_engine.engine.dataflow - INFO - Preparing Pathway computation
2025-01-10 21:25:05,069 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-10 21:25:05,152 - googleapiclient.discovery_cache - INFO - file_cache is only supported with oauth2client<4.0.0
2025-01-10 21:25:05,173 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-10 21:25:05,215 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-10 21:25:05,219 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-10 21:25:05,235 - pathway_engine.connectors.monitoring - INFO - PythonReader-0: 0 entries (1 minibatch(es)) have been sent to the engine
2025-01-10 21:25:05,235 - pathway_engine.connectors.monitoring - INFO - PythonReader-1: 0 entries (1 minibatch(es)) have been sent to the engine
2025-01-10 21:25:05,235 - pathway_engine.connectors.monitoring - INFO - PythonReader-2: 0 entries (1 minibatch(es)) have been sent to the engine
2025-01-10 21:25:05,236 - pathway_engine.connectors.monitoring - INFO - PythonReader-3: 0 entries (1 minibatch(es)) have been sent to the engine
2025-01-10 21:25:11,068 - pathway_engine.connectors.monitoring - INFO - PythonReader-0: 1 entries (4 minibatch(es)) have been sent to the engine
2025-01-10 21:25:11,743 - pikepdf._core - INFO - pikepdf C++ to Python logger bridge initialized
2025-01-10 21:25:23,903 - pathway_engine.connectors.monitoring - INFO - PythonReader-0: 0 entries (1 minibatch(es)) have been sent to the engine
2025-01-10 21:25:48,514 - pathway_engine.connectors.monitoring - INFO - PythonReader-0: 1 entries (2 minibatch(es)) have been sent to the engine
2025-01-10 21:26:05,026 - root - INFO - {"_type": "request_payload", "session_id": "uuid-624e1ed0-d4d6-44f8-a790-9dfed57c2c0c", "payload": {"query": "What is AI?", "k": 3}}
2025-01-10 21:26:07,525 - pathway_engine.connectors.monitoring - INFO - PythonReader-0: 0 entries (12 minibatch(es)) have been sent to the engine
2025-01-10 21:26:07,525 - pathway_engine.connectors.monitoring - INFO - PythonReader-1: 1 entries (139 minibatch(es)) have been sent to the engine
2025-01-10 21:26:07,793 - root - INFO - {"_type": "http_access", "method": "POST", "scheme": "http", "scheme_with_forwarded": "http", "host": "127.0.0.1:8745", "route": "/v1/retrieve", "content_type": "application/json", "user_agent": "python-requests/2.32.3", "unix_timestamp": 1736524565, "remote": "127.0.0.1", "session_id": "uuid-624e1ed0-d4d6-44f8-a790-9dfed57c2c0c", "headers": [{"header": "Host", "value": "127.0.0.1:8745"}, {"header": "User-Agent", "value": "python-requests/2.32.3"}, {"header": "Accept-Encoding", "value": "gzip, deflate"}, {"header": "Accept", "value": "*/*"}, {"header": "Connection", "value": "keep-alive"}, {"header": "Content-Type", "value": "application/json"}, {"header": "Content-Length", "value": "32"}], "status": 200, "time_elapsed": "2.768"}
2025-01-10 21:26:07,794 - aiohttp.access - INFO - 127.0.0.1 [10/Jan/2025:21:26:05 +0530] "POST /v1/retrieve HTTP/1.1" 200 5987 "-" "python-requests/2.32.3"
2025-01-10 21:26:12,573 - pathway_engine.connectors.monitoring - INFO - PythonReader-1: 0 entries (1208 minibatch(es)) have been sent to the engine
2025-01-10 21:28:00,661 - sentence_transformers.SentenceTransformer - INFO - Load pretrained SentenceTransformer: intfloat/e5-large-v2
2025-01-10 21:28:10,699 - py.warnings - WARNING - /home/destroy0p/AgnijBiswas/Publishability-of-Research/venv/lib/python3.12/site-packages/pathway/xpacks/llm/vector_store.py:218: UserWarning: `_metadata` column is not present in Table <pathway.Table schema={'data': typing.Any}>. Filtering will not work for this Table
  warnings.warn(

2025-01-10 21:28:10,760 - py.warnings - WARNING - /home/destroy0p/AgnijBiswas/Publishability-of-Research/venv/lib/python3.12/site-packages/beartype/_util/hint/pep/utilpeptest.py:311: BeartypeDecorHintPep585DeprecationWarning: PEP 484 type hint typing.Sequence[str] deprecated by PEP 585. This hint is scheduled for removal in the first Python version released after October 5th, 2025. To resolve this, import this hint from "beartype.typing" rather than "typing". For further commentary and alternatives, see also:
    https://beartype.readthedocs.io/en/latest/api_roar/#pep-585-deprecations
  warn(

2025-01-10 21:28:11,094 - pathway_engine.engine.dataflow - INFO - Preparing Pathway computation
2025-01-10 21:28:11,097 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-10 21:28:11,137 - googleapiclient.discovery_cache - INFO - file_cache is only supported with oauth2client<4.0.0
2025-01-10 21:28:11,150 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-10 21:28:11,163 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-10 21:28:11,168 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-10 21:28:11,177 - pathway_engine.connectors.monitoring - INFO - PythonReader-0: 0 entries (1 minibatch(es)) have been sent to the engine
2025-01-10 21:28:11,177 - pathway_engine.connectors.monitoring - INFO - PythonReader-1: 0 entries (1 minibatch(es)) have been sent to the engine
2025-01-10 21:28:11,177 - pathway_engine.connectors.monitoring - INFO - PythonReader-2: 0 entries (1 minibatch(es)) have been sent to the engine
2025-01-10 21:28:11,178 - pathway_engine.connectors.monitoring - INFO - PythonReader-3: 0 entries (1 minibatch(es)) have been sent to the engine
2025-01-10 21:28:20,096 - pathway_engine.connectors.monitoring - INFO - PythonReader-0: 1 entries (6 minibatch(es)) have been sent to the engine
2025-01-10 21:28:20,805 - pikepdf._core - INFO - pikepdf C++ to Python logger bridge initialized
2025-01-10 21:28:44,878 - pathway_engine.connectors.monitoring - INFO - PythonReader-0: 0 entries (1 minibatch(es)) have been sent to the engine
2025-01-10 21:29:03,677 - pathway_engine.connectors.monitoring - INFO - PythonReader-0: 1 entries (14 minibatch(es)) have been sent to the engine
2025-01-10 21:29:09,596 - pathway_engine.connectors.monitoring - INFO - PythonReader-0: 0 entries (18 minibatch(es)) have been sent to the engine
2025-01-10 21:29:11,075 - root - INFO - {"_type": "request_payload", "session_id": "uuid-fb96f223-9aab-4c24-824c-ae58e89b2fc9", "payload": {"query": "What is the best way to train a neural network?", "k": 3}}
2025-01-10 21:29:11,097 - pathway_engine.connectors.monitoring - INFO - PythonReader-1: 1 entries (1199 minibatch(es)) have been sent to the engine
2025-01-10 21:29:11,407 - root - INFO - {"_type": "http_access", "method": "POST", "scheme": "http", "scheme_with_forwarded": "http", "host": "127.0.0.1:8745", "route": "/v1/retrieve", "content_type": "application/json", "user_agent": "python-requests/2.32.3", "unix_timestamp": 1736524751, "remote": "127.0.0.1", "session_id": "uuid-fb96f223-9aab-4c24-824c-ae58e89b2fc9", "headers": [{"header": "Host", "value": "127.0.0.1:8745"}, {"header": "User-Agent", "value": "python-requests/2.32.3"}, {"header": "Accept-Encoding", "value": "gzip, deflate"}, {"header": "Accept", "value": "*/*"}, {"header": "Connection", "value": "keep-alive"}, {"header": "Content-Type", "value": "application/json"}, {"header": "Content-Length", "value": "68"}], "status": 200, "time_elapsed": "0.333"}
2025-01-10 21:29:11,408 - aiohttp.access - INFO - 127.0.0.1 [10/Jan/2025:21:29:11 +0530] "POST /v1/retrieve HTTP/1.1" 200 4999 "-" "python-requests/2.32.3"
2025-01-10 21:29:16,098 - pathway_engine.connectors.monitoring - INFO - PythonReader-1: 0 entries (100 minibatch(es)) have been sent to the engine
2025-01-10 21:52:55,420 - pathway_engine.connectors - ERROR - There had been an error processing the row read result: TimeoutError: The read operation timed out
2025-01-10 21:52:55,421 - pathway_engine.connectors.monitoring - INFO - PythonReader-0: 0 entries (951 minibatch(es)) have been sent to the engine
2025-01-10 21:52:55,421 - pathway_engine.connectors.monitoring - WARNING - PythonReader-0: Closing the data source
2025-01-10 22:02:38,530 - sentence_transformers.SentenceTransformer - INFO - Load pretrained SentenceTransformer: intfloat/e5-large-v2
2025-01-10 22:02:48,383 - py.warnings - WARNING - /home/destroy0p/AgnijBiswas/Publishability-of-Research/venv/lib/python3.12/site-packages/pathway/xpacks/llm/vector_store.py:218: UserWarning: `_metadata` column is not present in Table <pathway.Table schema={'data': typing.Any}>. Filtering will not work for this Table
  warnings.warn(

2025-01-10 22:02:48,485 - py.warnings - WARNING - /home/destroy0p/AgnijBiswas/Publishability-of-Research/venv/lib/python3.12/site-packages/beartype/_util/hint/pep/utilpeptest.py:311: BeartypeDecorHintPep585DeprecationWarning: PEP 484 type hint typing.Sequence[str] deprecated by PEP 585. This hint is scheduled for removal in the first Python version released after October 5th, 2025. To resolve this, import this hint from "beartype.typing" rather than "typing". For further commentary and alternatives, see also:
    https://beartype.readthedocs.io/en/latest/api_roar/#pep-585-deprecations
  warn(

2025-01-10 22:02:48,880 - pathway_engine.engine.dataflow - INFO - Preparing Pathway computation
2025-01-10 22:02:48,883 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-10 22:02:49,014 - googleapiclient.discovery_cache - INFO - file_cache is only supported with oauth2client<4.0.0
2025-01-10 22:02:49,049 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-10 22:02:49,103 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-10 22:02:49,113 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-10 22:02:49,129 - pathway_engine.connectors.monitoring - INFO - PythonReader-0: 0 entries (1 minibatch(es)) have been sent to the engine
2025-01-10 22:02:49,129 - pathway_engine.connectors.monitoring - INFO - PythonReader-1: 0 entries (1 minibatch(es)) have been sent to the engine
2025-01-10 22:02:49,129 - pathway_engine.connectors.monitoring - INFO - PythonReader-2: 0 entries (1 minibatch(es)) have been sent to the engine
2025-01-10 22:02:49,130 - pathway_engine.connectors.monitoring - INFO - PythonReader-3: 0 entries (1 minibatch(es)) have been sent to the engine
2025-01-10 22:02:56,383 - pathway_engine.connectors.monitoring - INFO - PythonReader-0: 1 entries (5 minibatch(es)) have been sent to the engine
2025-01-10 22:02:57,072 - pikepdf._core - INFO - pikepdf C++ to Python logger bridge initialized
2025-01-10 22:03:22,008 - pathway_engine.connectors.monitoring - INFO - PythonReader-0: 0 entries (1 minibatch(es)) have been sent to the engine
2025-01-10 22:03:40,663 - pathway_engine.connectors.monitoring - INFO - PythonReader-0: 1 entries (15 minibatch(es)) have been sent to the engine
2025-01-10 22:03:45,883 - pathway_engine.connectors.monitoring - INFO - PythonReader-0: 0 entries (17 minibatch(es)) have been sent to the engine
2025-01-10 22:03:48,832 - root - INFO - {"_type": "request_payload", "session_id": "uuid-3999ba05-feb6-424b-a459-276206d7b115", "payload": {"query": "What is the best way to train a neural network?", "k": 3}}
2025-01-10 22:03:48,847 - pathway_engine.connectors.monitoring - INFO - PythonReader-1: 1 entries (1195 minibatch(es)) have been sent to the engine
2025-01-10 22:03:49,152 - root - INFO - {"_type": "http_access", "method": "POST", "scheme": "http", "scheme_with_forwarded": "http", "host": "127.0.0.1:8745", "route": "/v1/retrieve", "content_type": "application/json", "user_agent": "python-requests/2.32.3", "unix_timestamp": 1736526828, "remote": "127.0.0.1", "session_id": "uuid-3999ba05-feb6-424b-a459-276206d7b115", "headers": [{"header": "Host", "value": "127.0.0.1:8745"}, {"header": "User-Agent", "value": "python-requests/2.32.3"}, {"header": "Accept-Encoding", "value": "gzip, deflate"}, {"header": "Accept", "value": "*/*"}, {"header": "Connection", "value": "keep-alive"}, {"header": "Content-Type", "value": "application/json"}, {"header": "Content-Length", "value": "68"}], "status": 200, "time_elapsed": "0.321"}
2025-01-10 22:03:49,154 - aiohttp.access - INFO - 127.0.0.1 [10/Jan/2025:22:03:48 +0530] "POST /v1/retrieve HTTP/1.1" 200 4999 "-" "python-requests/2.32.3"
2025-01-10 22:03:53,897 - pathway_engine.connectors.monitoring - INFO - PythonReader-1: 0 entries (101 minibatch(es)) have been sent to the engine
2025-01-11 20:08:16,134 - pathway_engine.connectors - ERROR - There had been an error processing the row read result: TimeoutError: The read operation timed out
2025-01-11 20:08:16,136 - pathway_engine.connectors.monitoring - INFO - PythonReader-0: 0 entries (52981 minibatch(es)) have been sent to the engine
2025-01-11 20:08:16,136 - pathway_engine.connectors.monitoring - WARNING - PythonReader-0: Closing the data source
2025-01-13 08:20:19,892 - sentence_transformers.SentenceTransformer - INFO - Load pretrained SentenceTransformer: intfloat/e5-large-v2
2025-01-13 08:20:26,840 - py.warnings - WARNING - /home/destroy0p/AgnijBiswas/Publishability-of-Research/venv/lib/python3.12/site-packages/pathway/xpacks/llm/vector_store.py:218: UserWarning: `_metadata` column is not present in Table <pathway.Table schema={'data': typing.Any}>. Filtering will not work for this Table
  warnings.warn(

2025-01-13 08:20:26,937 - py.warnings - WARNING - /home/destroy0p/AgnijBiswas/Publishability-of-Research/venv/lib/python3.12/site-packages/beartype/_util/hint/pep/utilpeptest.py:311: BeartypeDecorHintPep585DeprecationWarning: PEP 484 type hint typing.Sequence[str] deprecated by PEP 585. This hint is scheduled for removal in the first Python version released after October 5th, 2025. To resolve this, import this hint from "beartype.typing" rather than "typing". For further commentary and alternatives, see also:
    https://beartype.readthedocs.io/en/latest/api_roar/#pep-585-deprecations
  warn(

2025-01-13 08:20:27,313 - pathway_engine.engine.dataflow - INFO - Preparing Pathway computation
2025-01-13 08:20:27,328 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-13 08:20:27,410 - googleapiclient.discovery_cache - INFO - file_cache is only supported with oauth2client<4.0.0
2025-01-13 08:20:27,445 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-13 08:20:27,485 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-13 08:20:27,491 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-13 08:20:27,505 - pathway_engine.connectors.monitoring - INFO - PythonReader-0: 0 entries (1 minibatch(es)) have been sent to the engine
2025-01-13 08:20:27,506 - pathway_engine.connectors.monitoring - INFO - PythonReader-1: 0 entries (1 minibatch(es)) have been sent to the engine
2025-01-13 08:20:27,506 - pathway_engine.connectors.monitoring - INFO - PythonReader-2: 0 entries (1 minibatch(es)) have been sent to the engine
2025-01-13 08:20:27,506 - pathway_engine.connectors.monitoring - INFO - PythonReader-3: 0 entries (1 minibatch(es)) have been sent to the engine
2025-01-13 08:20:34,828 - pathway_engine.connectors.monitoring - INFO - PythonReader-0: 1 entries (5 minibatch(es)) have been sent to the engine
2025-01-13 08:20:35,786 - pikepdf._core - INFO - pikepdf C++ to Python logger bridge initialized
2025-01-13 08:20:42,007 - pathway_engine.connectors.monitoring - INFO - PythonReader-0: 1 entries (3 minibatch(es)) have been sent to the engine
2025-01-13 08:21:03,096 - pathway_engine.connectors.monitoring - INFO - PythonReader-0: 0 entries (2 minibatch(es)) have been sent to the engine
2025-01-13 08:21:27,299 - root - INFO - {"_type": "request_payload", "session_id": "uuid-f62c66d0-3f9a-4ed1-9c15-de73561ba4fd", "payload": {"query": "What is the best way to train a neural network?", "k": 3}}
2025-01-13 08:21:27,343 - pathway_engine.connectors.monitoring - INFO - PythonReader-1: 1 entries (1197 minibatch(es)) have been sent to the engine
2025-01-13 08:21:27,633 - root - INFO - {"_type": "http_access", "method": "POST", "scheme": "http", "scheme_with_forwarded": "http", "host": "127.0.0.1:8745", "route": "/v1/retrieve", "content_type": "application/json", "user_agent": "python-requests/2.32.3", "unix_timestamp": 1736736687, "remote": "127.0.0.1", "session_id": "uuid-f62c66d0-3f9a-4ed1-9c15-de73561ba4fd", "headers": [{"header": "Host", "value": "127.0.0.1:8745"}, {"header": "User-Agent", "value": "python-requests/2.32.3"}, {"header": "Accept-Encoding", "value": "gzip, deflate"}, {"header": "Accept", "value": "*/*"}, {"header": "Connection", "value": "keep-alive"}, {"header": "Content-Type", "value": "application/json"}, {"header": "Content-Length", "value": "68"}], "status": 200, "time_elapsed": "0.334"}
2025-01-13 08:21:27,634 - aiohttp.access - INFO - 127.0.0.1 [13/Jan/2025:08:21:27 +0530] "POST /v1/retrieve HTTP/1.1" 200 4999 "-" "python-requests/2.32.3"
2025-01-13 08:21:32,393 - pathway_engine.connectors.monitoring - INFO - PythonReader-1: 0 entries (101 minibatch(es)) have been sent to the engine
2025-01-13 08:25:08,389 - sentence_transformers.SentenceTransformer - INFO - Load pretrained SentenceTransformer: intfloat/e5-large-v2
2025-01-13 08:25:24,814 - py.warnings - WARNING - /home/destroy0p/AgnijBiswas/Publishability-of-Research/venv/lib/python3.12/site-packages/pathway/xpacks/llm/vector_store.py:218: UserWarning: `_metadata` column is not present in Table <pathway.Table schema={'data': typing.Any}>. Filtering will not work for this Table
  warnings.warn(

2025-01-13 08:25:24,876 - py.warnings - WARNING - /home/destroy0p/AgnijBiswas/Publishability-of-Research/venv/lib/python3.12/site-packages/beartype/_util/hint/pep/utilpeptest.py:311: BeartypeDecorHintPep585DeprecationWarning: PEP 484 type hint typing.Sequence[str] deprecated by PEP 585. This hint is scheduled for removal in the first Python version released after October 5th, 2025. To resolve this, import this hint from "beartype.typing" rather than "typing". For further commentary and alternatives, see also:
    https://beartype.readthedocs.io/en/latest/api_roar/#pep-585-deprecations
  warn(

2025-01-13 08:25:25,262 - pathway_engine.engine.dataflow - INFO - Preparing Pathway computation
2025-01-13 08:25:25,264 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-13 08:25:25,324 - googleapiclient.discovery_cache - INFO - file_cache is only supported with oauth2client<4.0.0
2025-01-13 08:25:25,344 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-13 08:25:25,379 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-13 08:25:25,385 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-13 08:25:25,396 - pathway_engine.connectors.monitoring - INFO - PythonReader-0: 0 entries (1 minibatch(es)) have been sent to the engine
2025-01-13 08:25:25,396 - pathway_engine.connectors.monitoring - INFO - PythonReader-1: 0 entries (1 minibatch(es)) have been sent to the engine
2025-01-13 08:25:25,396 - pathway_engine.connectors.monitoring - INFO - PythonReader-2: 0 entries (1 minibatch(es)) have been sent to the engine
2025-01-13 08:25:25,396 - pathway_engine.connectors.monitoring - INFO - PythonReader-3: 0 entries (1 minibatch(es)) have been sent to the engine
2025-01-13 08:25:31,264 - pathway_engine.connectors.monitoring - INFO - PythonReader-0: 1 entries (4 minibatch(es)) have been sent to the engine
2025-01-13 08:25:31,895 - pikepdf._core - INFO - pikepdf C++ to Python logger bridge initialized
2025-01-13 08:25:50,738 - sentence_transformers.SentenceTransformer - INFO - Load pretrained SentenceTransformer: intfloat/e5-large-v2
2025-01-13 08:25:56,733 - py.warnings - WARNING - /home/destroy0p/AgnijBiswas/Publishability-of-Research/venv/lib/python3.12/site-packages/pathway/xpacks/llm/vector_store.py:218: UserWarning: `_metadata` column is not present in Table <pathway.Table schema={'data': typing.Any}>. Filtering will not work for this Table
  warnings.warn(

2025-01-13 08:25:56,801 - py.warnings - WARNING - /home/destroy0p/AgnijBiswas/Publishability-of-Research/venv/lib/python3.12/site-packages/beartype/_util/hint/pep/utilpeptest.py:311: BeartypeDecorHintPep585DeprecationWarning: PEP 484 type hint typing.Sequence[str] deprecated by PEP 585. This hint is scheduled for removal in the first Python version released after October 5th, 2025. To resolve this, import this hint from "beartype.typing" rather than "typing". For further commentary and alternatives, see also:
    https://beartype.readthedocs.io/en/latest/api_roar/#pep-585-deprecations
  warn(

2025-01-13 08:25:57,147 - pathway_engine.engine.dataflow - INFO - Preparing Pathway computation
2025-01-13 08:25:57,149 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-13 08:25:57,215 - googleapiclient.discovery_cache - INFO - file_cache is only supported with oauth2client<4.0.0
2025-01-13 08:25:57,231 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-13 08:25:57,244 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-13 08:25:57,246 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-13 08:25:57,249 - pathway_engine.connectors.monitoring - INFO - PythonReader-0: 0 entries (1 minibatch(es)) have been sent to the engine
2025-01-13 08:25:57,250 - pathway_engine.connectors.monitoring - INFO - PythonReader-1: 0 entries (1 minibatch(es)) have been sent to the engine
2025-01-13 08:25:57,250 - pathway_engine.connectors.monitoring - INFO - PythonReader-2: 0 entries (1 minibatch(es)) have been sent to the engine
2025-01-13 08:25:57,250 - pathway_engine.connectors.monitoring - INFO - PythonReader-3: 0 entries (1 minibatch(es)) have been sent to the engine
2025-01-13 08:26:03,149 - pathway_engine.connectors.monitoring - INFO - PythonReader-0: 1 entries (4 minibatch(es)) have been sent to the engine
2025-01-13 08:26:03,804 - pikepdf._core - INFO - pikepdf C++ to Python logger bridge initialized
2025-01-13 08:26:24,969 - pathway_engine.connectors.monitoring - INFO - PythonReader-0: 0 entries (1 minibatch(es)) have been sent to the engine
2025-01-13 08:26:42,055 - pathway_engine.connectors.monitoring - INFO - PythonReader-0: 1 entries (14 minibatch(es)) have been sent to the engine
2025-01-13 08:26:48,149 - pathway_engine.connectors.monitoring - INFO - PythonReader-0: 0 entries (15 minibatch(es)) have been sent to the engine
2025-01-13 08:26:57,128 - root - INFO - {"_type": "request_payload", "session_id": "uuid-321087f0-1541-4f57-b696-8203417ae00c", "payload": {"query": "What is the best way to train a neural network?", "k": 3}}
2025-01-13 08:26:57,131 - pathway_engine.connectors.monitoring - INFO - PythonReader-1: 1 entries (1198 minibatch(es)) have been sent to the engine
2025-01-13 08:26:57,507 - root - INFO - {"_type": "http_access", "method": "POST", "scheme": "http", "scheme_with_forwarded": "http", "host": "127.0.0.1:8745", "route": "/v1/retrieve", "content_type": "application/json", "user_agent": "python-requests/2.32.3", "unix_timestamp": 1736737017, "remote": "127.0.0.1", "session_id": "uuid-321087f0-1541-4f57-b696-8203417ae00c", "headers": [{"header": "Host", "value": "127.0.0.1:8745"}, {"header": "User-Agent", "value": "python-requests/2.32.3"}, {"header": "Accept-Encoding", "value": "gzip, deflate"}, {"header": "Accept", "value": "*/*"}, {"header": "Connection", "value": "keep-alive"}, {"header": "Content-Type", "value": "application/json"}, {"header": "Content-Length", "value": "68"}], "status": 200, "time_elapsed": "0.379"}
2025-01-13 08:26:57,509 - aiohttp.access - INFO - 127.0.0.1 [13/Jan/2025:08:26:57 +0530] "POST /v1/retrieve HTTP/1.1" 200 4999 "-" "python-requests/2.32.3"
2025-01-13 08:27:02,131 - pathway_engine.connectors.monitoring - INFO - PythonReader-1: 0 entries (100 minibatch(es)) have been sent to the engine
2025-01-13 08:29:32,653 - sentence_transformers.SentenceTransformer - INFO - Load pretrained SentenceTransformer: intfloat/e5-large-v2
2025-01-13 08:29:38,712 - py.warnings - WARNING - /home/destroy0p/AgnijBiswas/Publishability-of-Research/venv/lib/python3.12/site-packages/pathway/internals/parse_graph.py:249: UserWarning: There are operators in the computation graph that haven't been used. Use pathway.run() (or similar) to run the computation involving these nodes.
  warnings.warn(

2025-01-13 08:30:39,752 - sentence_transformers.SentenceTransformer - INFO - Load pretrained SentenceTransformer: intfloat/e5-large-v2
2025-01-13 08:30:59,020 - sentence_transformers.SentenceTransformer - INFO - Load pretrained SentenceTransformer: intfloat/e5-large-v2
2025-01-13 08:31:03,715 - py.warnings - WARNING - /home/destroy0p/AgnijBiswas/Publishability-of-Research/venv/lib/python3.12/site-packages/pathway/internals/parse_graph.py:249: UserWarning: There are operators in the computation graph that haven't been used. Use pathway.run() (or similar) to run the computation involving these nodes.
  warnings.warn(

2025-01-13 08:31:56,702 - sentence_transformers.SentenceTransformer - INFO - Load pretrained SentenceTransformer: intfloat/e5-large-v2
2025-01-13 08:32:01,512 - py.warnings - WARNING - /home/destroy0p/AgnijBiswas/Publishability-of-Research/venv/lib/python3.12/site-packages/pathway/xpacks/llm/vector_store.py:218: UserWarning: `_metadata` column is not present in Table <pathway.Table schema={'data': typing.Any}>. Filtering will not work for this Table
  warnings.warn(

2025-01-13 08:32:01,565 - sentence_transformers.SentenceTransformer - INFO - Load pretrained SentenceTransformer: intfloat/e5-large-v2
2025-01-13 08:32:04,998 - py.warnings - WARNING - /home/destroy0p/AgnijBiswas/Publishability-of-Research/venv/lib/python3.12/site-packages/beartype/_util/hint/pep/utilpeptest.py:311: BeartypeDecorHintPep585DeprecationWarning: PEP 484 type hint typing.Sequence[str] deprecated by PEP 585. This hint is scheduled for removal in the first Python version released after October 5th, 2025. To resolve this, import this hint from "beartype.typing" rather than "typing". For further commentary and alternatives, see also:
    https://beartype.readthedocs.io/en/latest/api_roar/#pep-585-deprecations
  warn(

2025-01-13 08:32:05,179 - pathway_engine.engine.dataflow - INFO - Preparing Pathway computation
2025-01-13 08:32:05,181 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-13 08:32:05,244 - googleapiclient.discovery_cache - INFO - file_cache is only supported with oauth2client<4.0.0
2025-01-13 08:32:05,265 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-13 08:32:05,292 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-13 08:32:05,297 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-13 08:32:05,306 - pathway_engine.connectors.monitoring - INFO - PythonReader-0: 0 entries (1 minibatch(es)) have been sent to the engine
2025-01-13 08:32:05,307 - pathway_engine.connectors.monitoring - INFO - PythonReader-1: 0 entries (1 minibatch(es)) have been sent to the engine
2025-01-13 08:32:05,307 - pathway_engine.connectors.monitoring - INFO - PythonReader-2: 0 entries (1 minibatch(es)) have been sent to the engine
2025-01-13 08:32:05,307 - pathway_engine.connectors.monitoring - INFO - PythonReader-3: 0 entries (1 minibatch(es)) have been sent to the engine
2025-01-13 08:32:11,182 - pathway_engine.connectors.monitoring - INFO - PythonReader-0: 1 entries (4 minibatch(es)) have been sent to the engine
2025-01-13 08:32:11,827 - pikepdf._core - INFO - pikepdf C++ to Python logger bridge initialized
2025-01-13 08:32:32,607 - pathway_engine.connectors.monitoring - INFO - PythonReader-0: 0 entries (1 minibatch(es)) have been sent to the engine
2025-01-13 08:32:47,946 - pathway_engine.connectors.monitoring - INFO - PythonReader-0: 1 entries (14 minibatch(es)) have been sent to the engine
2025-01-13 08:32:53,182 - pathway_engine.connectors.monitoring - INFO - PythonReader-0: 0 entries (13 minibatch(es)) have been sent to the engine
2025-01-13 08:34:50,844 - sentence_transformers.SentenceTransformer - INFO - Load pretrained SentenceTransformer: intfloat/e5-large-v2
2025-01-13 08:34:56,582 - py.warnings - WARNING - /home/destroy0p/AgnijBiswas/Publishability-of-Research/venv/lib/python3.12/site-packages/pathway/xpacks/llm/vector_store.py:218: UserWarning: `_metadata` column is not present in Table <pathway.Table schema={'data': typing.Any}>. Filtering will not work for this Table
  warnings.warn(

2025-01-13 08:34:56,640 - sentence_transformers.SentenceTransformer - INFO - Load pretrained SentenceTransformer: intfloat/e5-large-v2
2025-01-13 08:35:00,352 - py.warnings - WARNING - /home/destroy0p/AgnijBiswas/Publishability-of-Research/venv/lib/python3.12/site-packages/beartype/_util/hint/pep/utilpeptest.py:311: BeartypeDecorHintPep585DeprecationWarning: PEP 484 type hint typing.Sequence[str] deprecated by PEP 585. This hint is scheduled for removal in the first Python version released after October 5th, 2025. To resolve this, import this hint from "beartype.typing" rather than "typing". For further commentary and alternatives, see also:
    https://beartype.readthedocs.io/en/latest/api_roar/#pep-585-deprecations
  warn(

2025-01-13 08:35:00,526 - pathway_engine.engine.dataflow - INFO - Preparing Pathway computation
2025-01-13 08:35:00,591 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-13 08:35:00,594 - googleapiclient.discovery_cache - INFO - file_cache is only supported with oauth2client<4.0.0
2025-01-13 08:35:00,614 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-13 08:35:00,661 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-13 08:35:00,662 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-13 08:35:00,670 - pathway_engine.connectors.monitoring - INFO - PythonReader-0: 0 entries (1 minibatch(es)) have been sent to the engine
2025-01-13 08:35:00,670 - pathway_engine.connectors.monitoring - INFO - PythonReader-1: 0 entries (1 minibatch(es)) have been sent to the engine
2025-01-13 08:35:00,670 - pathway_engine.connectors.monitoring - INFO - PythonReader-2: 0 entries (1 minibatch(es)) have been sent to the engine
2025-01-13 08:35:00,670 - pathway_engine.connectors.monitoring - INFO - PythonReader-3: 0 entries (1 minibatch(es)) have been sent to the engine
2025-01-13 08:35:06,526 - pathway_engine.connectors.monitoring - INFO - PythonReader-0: 1 entries (4 minibatch(es)) have been sent to the engine
2025-01-13 08:35:07,145 - pikepdf._core - INFO - pikepdf C++ to Python logger bridge initialized
2025-01-13 08:35:27,915 - pathway_engine.connectors.monitoring - INFO - PythonReader-0: 0 entries (1 minibatch(es)) have been sent to the engine
2025-01-13 08:35:43,200 - pathway_engine.connectors.monitoring - INFO - PythonReader-0: 1 entries (14 minibatch(es)) have been sent to the engine
2025-01-13 08:35:48,526 - pathway_engine.connectors.monitoring - INFO - PythonReader-0: 0 entries (13 minibatch(es)) have been sent to the engine
2025-01-13 08:48:40,094 - sentence_transformers.SentenceTransformer - INFO - Load pretrained SentenceTransformer: intfloat/e5-large-v2
2025-01-13 08:48:45,300 - py.warnings - WARNING - /home/destroy0p/AgnijBiswas/Publishability-of-Research/venv/lib/python3.12/site-packages/pathway/xpacks/llm/vector_store.py:218: UserWarning: `_metadata` column is not present in Table <pathway.Table schema={'data': typing.Any}>. Filtering will not work for this Table
  warnings.warn(

2025-01-13 08:48:45,384 - sentence_transformers.SentenceTransformer - INFO - Load pretrained SentenceTransformer: intfloat/e5-large-v2
2025-01-13 08:48:49,299 - py.warnings - WARNING - /home/destroy0p/AgnijBiswas/Publishability-of-Research/venv/lib/python3.12/site-packages/beartype/_util/hint/pep/utilpeptest.py:311: BeartypeDecorHintPep585DeprecationWarning: PEP 484 type hint typing.Sequence[str] deprecated by PEP 585. This hint is scheduled for removal in the first Python version released after October 5th, 2025. To resolve this, import this hint from "beartype.typing" rather than "typing". For further commentary and alternatives, see also:
    https://beartype.readthedocs.io/en/latest/api_roar/#pep-585-deprecations
  warn(

2025-01-13 08:48:49,509 - pathway_engine.engine.dataflow - INFO - Preparing Pathway computation
2025-01-13 08:48:49,512 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-13 08:48:49,614 - googleapiclient.discovery_cache - INFO - file_cache is only supported with oauth2client<4.0.0
2025-01-13 08:48:49,639 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-13 08:48:49,674 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-13 08:48:49,680 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-13 08:48:49,698 - pathway_engine.connectors.monitoring - INFO - PythonReader-0: 0 entries (1 minibatch(es)) have been sent to the engine
2025-01-13 08:48:49,698 - pathway_engine.connectors.monitoring - INFO - PythonReader-1: 0 entries (1 minibatch(es)) have been sent to the engine
2025-01-13 08:48:49,699 - pathway_engine.connectors.monitoring - INFO - PythonReader-2: 0 entries (1 minibatch(es)) have been sent to the engine
2025-01-13 08:48:49,699 - pathway_engine.connectors.monitoring - INFO - PythonReader-3: 0 entries (1 minibatch(es)) have been sent to the engine
2025-01-13 08:48:55,511 - pathway_engine.connectors.monitoring - INFO - PythonReader-0: 1 entries (4 minibatch(es)) have been sent to the engine
2025-01-13 08:48:56,165 - pikepdf._core - INFO - pikepdf C++ to Python logger bridge initialized
2025-01-13 08:49:17,173 - pathway_engine.connectors.monitoring - INFO - PythonReader-0: 0 entries (1 minibatch(es)) have been sent to the engine
2025-01-13 08:49:33,199 - pathway_engine.connectors.monitoring - INFO - PythonReader-0: 1 entries (14 minibatch(es)) have been sent to the engine
2025-01-13 08:49:39,011 - pathway_engine.connectors.monitoring - INFO - PythonReader-0: 0 entries (14 minibatch(es)) have been sent to the engine
2025-01-13 09:06:43,698 - sentence_transformers.SentenceTransformer - INFO - Load pretrained SentenceTransformer: intfloat/e5-large-v2
2025-01-13 09:06:49,914 - py.warnings - WARNING - /home/destroy0p/AgnijBiswas/Publishability-of-Research/venv/lib/python3.12/site-packages/pathway/xpacks/llm/vector_store.py:218: UserWarning: `_metadata` column is not present in Table <pathway.Table schema={'data': typing.Any}>. Filtering will not work for this Table
  warnings.warn(

2025-01-13 09:06:49,967 - py.warnings - WARNING - /home/destroy0p/AgnijBiswas/Publishability-of-Research/venv/lib/python3.12/site-packages/beartype/_util/hint/pep/utilpeptest.py:311: BeartypeDecorHintPep585DeprecationWarning: PEP 484 type hint typing.Sequence[str] deprecated by PEP 585. This hint is scheduled for removal in the first Python version released after October 5th, 2025. To resolve this, import this hint from "beartype.typing" rather than "typing". For further commentary and alternatives, see also:
    https://beartype.readthedocs.io/en/latest/api_roar/#pep-585-deprecations
  warn(

2025-01-13 09:06:50,323 - pathway_engine.engine.dataflow - INFO - Preparing Pathway computation
2025-01-13 09:06:50,325 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-13 09:06:50,388 - googleapiclient.discovery_cache - INFO - file_cache is only supported with oauth2client<4.0.0
2025-01-13 09:06:50,405 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-13 09:06:50,420 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-13 09:06:50,422 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-13 09:06:50,425 - pathway_engine.connectors.monitoring - INFO - PythonReader-0: 0 entries (1 minibatch(es)) have been sent to the engine
2025-01-13 09:06:50,425 - pathway_engine.connectors.monitoring - INFO - PythonReader-1: 0 entries (1 minibatch(es)) have been sent to the engine
2025-01-13 09:06:50,425 - pathway_engine.connectors.monitoring - INFO - PythonReader-2: 0 entries (1 minibatch(es)) have been sent to the engine
2025-01-13 09:06:50,425 - pathway_engine.connectors.monitoring - INFO - PythonReader-3: 0 entries (1 minibatch(es)) have been sent to the engine
2025-01-13 09:06:56,325 - pathway_engine.connectors.monitoring - INFO - PythonReader-0: 1 entries (4 minibatch(es)) have been sent to the engine
2025-01-13 09:06:56,940 - pikepdf._core - INFO - pikepdf C++ to Python logger bridge initialized
2025-01-13 09:07:18,643 - pathway_engine.connectors.monitoring - INFO - PythonReader-0: 0 entries (1 minibatch(es)) have been sent to the engine
2025-01-13 09:07:34,797 - pathway_engine.connectors.monitoring - INFO - PythonReader-0: 1 entries (15 minibatch(es)) have been sent to the engine
2025-01-13 09:07:39,825 - pathway_engine.connectors.monitoring - INFO - PythonReader-0: 0 entries (13 minibatch(es)) have been sent to the engine
2025-01-13 09:07:50,305 - root - INFO - {"_type": "request_payload", "session_id": "uuid-049113b7-3383-4640-a355-3b6152d977f5", "payload": {"query": "What is the best way to train a neural network?", "k": 3}}
2025-01-13 09:07:50,354 - pathway_engine.connectors.monitoring - INFO - PythonReader-1: 1 entries (1199 minibatch(es)) have been sent to the engine
2025-01-13 09:07:50,654 - root - INFO - {"_type": "http_access", "method": "POST", "scheme": "http", "scheme_with_forwarded": "http", "host": "127.0.0.1:8745", "route": "/v1/retrieve", "content_type": "application/json", "user_agent": "python-requests/2.32.3", "unix_timestamp": 1736739470, "remote": "127.0.0.1", "session_id": "uuid-049113b7-3383-4640-a355-3b6152d977f5", "headers": [{"header": "Host", "value": "127.0.0.1:8745"}, {"header": "User-Agent", "value": "python-requests/2.32.3"}, {"header": "Accept-Encoding", "value": "gzip, deflate"}, {"header": "Accept", "value": "*/*"}, {"header": "Connection", "value": "keep-alive"}, {"header": "Content-Type", "value": "application/json"}, {"header": "Content-Length", "value": "68"}], "status": 200, "time_elapsed": "0.350"}
2025-01-13 09:07:50,656 - aiohttp.access - INFO - 127.0.0.1 [13/Jan/2025:09:07:50 +0530] "POST /v1/retrieve HTTP/1.1" 200 4999 "-" "python-requests/2.32.3"
2025-01-13 09:07:55,354 - pathway_engine.connectors.monitoring - INFO - PythonReader-1: 0 entries (100 minibatch(es)) have been sent to the engine
2025-01-13 09:08:23,809 - sentence_transformers.SentenceTransformer - INFO - Load pretrained SentenceTransformer: intfloat/e5-large-v2
2025-01-13 09:08:28,986 - py.warnings - WARNING - /home/destroy0p/AgnijBiswas/Publishability-of-Research/venv/lib/python3.12/site-packages/pathway/xpacks/llm/vector_store.py:218: UserWarning: `_metadata` column is not present in Table <pathway.Table schema={'data': typing.Any}>. Filtering will not work for this Table
  warnings.warn(

2025-01-13 09:08:29,072 - py.warnings - WARNING - /home/destroy0p/AgnijBiswas/Publishability-of-Research/venv/lib/python3.12/site-packages/beartype/_util/hint/pep/utilpeptest.py:311: BeartypeDecorHintPep585DeprecationWarning: PEP 484 type hint typing.Sequence[str] deprecated by PEP 585. This hint is scheduled for removal in the first Python version released after October 5th, 2025. To resolve this, import this hint from "beartype.typing" rather than "typing". For further commentary and alternatives, see also:
    https://beartype.readthedocs.io/en/latest/api_roar/#pep-585-deprecations
  warn(

2025-01-13 09:08:29,415 - pathway_engine.engine.dataflow - INFO - Preparing Pathway computation
2025-01-13 09:08:29,418 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-13 09:08:29,460 - googleapiclient.discovery_cache - INFO - file_cache is only supported with oauth2client<4.0.0
2025-01-13 09:08:29,474 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-13 09:08:29,489 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-13 09:08:29,491 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-13 09:08:29,496 - pathway_engine.connectors.monitoring - INFO - PythonReader-0: 0 entries (1 minibatch(es)) have been sent to the engine
2025-01-13 09:08:29,496 - pathway_engine.connectors.monitoring - INFO - PythonReader-1: 0 entries (1 minibatch(es)) have been sent to the engine
2025-01-13 09:08:29,496 - pathway_engine.connectors.monitoring - INFO - PythonReader-2: 0 entries (1 minibatch(es)) have been sent to the engine
2025-01-13 09:08:29,496 - pathway_engine.connectors.monitoring - INFO - PythonReader-3: 0 entries (1 minibatch(es)) have been sent to the engine
2025-01-13 09:08:35,418 - pathway_engine.connectors.monitoring - INFO - PythonReader-0: 1 entries (4 minibatch(es)) have been sent to the engine
2025-01-13 09:08:36,047 - pikepdf._core - INFO - pikepdf C++ to Python logger bridge initialized
2025-01-13 09:08:57,167 - pathway_engine.connectors.monitoring - INFO - PythonReader-0: 0 entries (1 minibatch(es)) have been sent to the engine
2025-01-13 09:09:14,185 - pathway_engine.connectors.monitoring - INFO - PythonReader-0: 1 entries (14 minibatch(es)) have been sent to the engine
2025-01-13 09:09:20,417 - pathway_engine.connectors.monitoring - INFO - PythonReader-0: 0 entries (15 minibatch(es)) have been sent to the engine
2025-01-13 09:09:29,396 - root - INFO - {"_type": "request_payload", "session_id": "uuid-f2385263-3a98-4e14-a49b-605aefca5e53", "payload": {"query": "What is the best way to train a neural network?", "k": 3}}
2025-01-13 09:09:29,423 - pathway_engine.connectors.monitoring - INFO - PythonReader-1: 1 entries (1199 minibatch(es)) have been sent to the engine
2025-01-13 09:09:29,713 - root - INFO - {"_type": "http_access", "method": "POST", "scheme": "http", "scheme_with_forwarded": "http", "host": "127.0.0.1:8745", "route": "/v1/retrieve", "content_type": "application/json", "user_agent": "python-requests/2.32.3", "unix_timestamp": 1736739569, "remote": "127.0.0.1", "session_id": "uuid-f2385263-3a98-4e14-a49b-605aefca5e53", "headers": [{"header": "Host", "value": "127.0.0.1:8745"}, {"header": "User-Agent", "value": "python-requests/2.32.3"}, {"header": "Accept-Encoding", "value": "gzip, deflate"}, {"header": "Accept", "value": "*/*"}, {"header": "Connection", "value": "keep-alive"}, {"header": "Content-Type", "value": "application/json"}, {"header": "Content-Length", "value": "68"}], "status": 200, "time_elapsed": "0.317"}
2025-01-13 09:09:29,713 - aiohttp.access - INFO - 127.0.0.1 [13/Jan/2025:09:09:29 +0530] "POST /v1/retrieve HTTP/1.1" 200 4999 "-" "python-requests/2.32.3"
2025-01-13 09:09:34,423 - pathway_engine.connectors.monitoring - INFO - PythonReader-1: 0 entries (100 minibatch(es)) have been sent to the engine
2025-01-13 10:25:30,037 - sentence_transformers.SentenceTransformer - INFO - Load pretrained SentenceTransformer: intfloat/e5-large-v2
2025-01-13 10:25:36,088 - py.warnings - WARNING - /home/destroy0p/AgnijBiswas/Publishability-of-Research/venv/lib/python3.12/site-packages/pathway/xpacks/llm/vector_store.py:218: UserWarning: `_metadata` column is not present in Table <pathway.Table schema={'data': typing.Any}>. Filtering will not work for this Table
  warnings.warn(

2025-01-13 10:25:36,145 - py.warnings - WARNING - /home/destroy0p/AgnijBiswas/Publishability-of-Research/venv/lib/python3.12/site-packages/beartype/_util/hint/pep/utilpeptest.py:311: BeartypeDecorHintPep585DeprecationWarning: PEP 484 type hint typing.Sequence[str] deprecated by PEP 585. This hint is scheduled for removal in the first Python version released after October 5th, 2025. To resolve this, import this hint from "beartype.typing" rather than "typing". For further commentary and alternatives, see also:
    https://beartype.readthedocs.io/en/latest/api_roar/#pep-585-deprecations
  warn(

2025-01-13 10:25:36,574 - pathway_engine.engine.dataflow - INFO - Preparing Pathway computation
2025-01-13 10:25:36,575 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-13 10:25:36,622 - googleapiclient.discovery_cache - INFO - file_cache is only supported with oauth2client<4.0.0
2025-01-13 10:25:36,657 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-13 10:25:36,686 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-13 10:25:36,694 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-13 10:25:36,710 - pathway_engine.connectors.monitoring - INFO - PythonReader-0: 0 entries (1 minibatch(es)) have been sent to the engine
2025-01-13 10:25:36,710 - pathway_engine.connectors.monitoring - INFO - PythonReader-1: 0 entries (1 minibatch(es)) have been sent to the engine
2025-01-13 10:25:36,710 - pathway_engine.connectors.monitoring - INFO - PythonReader-2: 0 entries (1 minibatch(es)) have been sent to the engine
2025-01-13 10:25:36,710 - pathway_engine.connectors.monitoring - INFO - PythonReader-3: 0 entries (1 minibatch(es)) have been sent to the engine
2025-01-13 10:25:42,576 - pathway_engine.connectors.monitoring - INFO - PythonReader-0: 1 entries (4 minibatch(es)) have been sent to the engine
2025-01-13 10:25:43,184 - pikepdf._core - INFO - pikepdf C++ to Python logger bridge initialized
2025-01-13 10:26:03,890 - pathway_engine.connectors.monitoring - INFO - PythonReader-0: 0 entries (1 minibatch(es)) have been sent to the engine
2025-01-13 10:26:20,116 - pathway_engine.connectors.monitoring - INFO - PythonReader-0: 1 entries (14 minibatch(es)) have been sent to the engine
2025-01-13 10:26:26,076 - pathway_engine.connectors.monitoring - INFO - PythonReader-0: 0 entries (14 minibatch(es)) have been sent to the engine
2025-01-13 10:26:36,553 - root - INFO - {"_type": "request_payload", "session_id": "uuid-f52a46b8-812c-450d-b033-d2757395bc86", "payload": {"query": "What is the best way to train a neural network?", "k": 3}}
2025-01-13 10:26:36,557 - pathway_engine.connectors.monitoring - INFO - PythonReader-1: 1 entries (1197 minibatch(es)) have been sent to the engine
2025-01-13 10:26:36,850 - root - INFO - {"_type": "http_access", "method": "POST", "scheme": "http", "scheme_with_forwarded": "http", "host": "127.0.0.1:8745", "route": "/v1/retrieve", "content_type": "application/json", "user_agent": "python-requests/2.32.3", "unix_timestamp": 1736744196, "remote": "127.0.0.1", "session_id": "uuid-f52a46b8-812c-450d-b033-d2757395bc86", "headers": [{"header": "Host", "value": "127.0.0.1:8745"}, {"header": "User-Agent", "value": "python-requests/2.32.3"}, {"header": "Accept-Encoding", "value": "gzip, deflate"}, {"header": "Accept", "value": "*/*"}, {"header": "Connection", "value": "keep-alive"}, {"header": "Content-Type", "value": "application/json"}, {"header": "Content-Length", "value": "68"}], "status": 200, "time_elapsed": "0.298"}
2025-01-13 10:26:36,851 - aiohttp.access - INFO - 127.0.0.1 [13/Jan/2025:10:26:36 +0530] "POST /v1/retrieve HTTP/1.1" 200 4999 "-" "python-requests/2.32.3"
2025-01-13 10:26:41,607 - pathway_engine.connectors.monitoring - INFO - PythonReader-1: 0 entries (101 minibatch(es)) have been sent to the engine
2025-01-13 21:17:46,625 - sentence_transformers.SentenceTransformer - INFO - Load pretrained SentenceTransformer: intfloat/e5-large-v2
2025-01-13 21:18:05,485 - py.warnings - WARNING - /home/destroy0p/AgnijBiswas/Publishability-of-Research/venv/lib/python3.12/site-packages/pathway/xpacks/llm/vector_store.py:218: UserWarning: `_metadata` column is not present in Table <pathway.Table schema={'data': typing.Any}>. Filtering will not work for this Table
  warnings.warn(

2025-01-13 21:18:05,569 - py.warnings - WARNING - /home/destroy0p/AgnijBiswas/Publishability-of-Research/venv/lib/python3.12/site-packages/pathway/internals/parse_graph.py:249: UserWarning: There are operators in the computation graph that haven't been used. Use pathway.run() (or similar) to run the computation involving these nodes.
  warnings.warn(

2025-01-13 21:50:21,151 - httpx - INFO - HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2025-01-13 21:51:43,584 - httpx - INFO - HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2025-01-13 21:51:45,118 - httpx - INFO - HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2025-01-13 21:54:25,581 - httpx - INFO - HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2025-01-13 21:54:26,808 - httpx - INFO - HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2025-01-13 21:54:28,753 - httpx - INFO - HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2025-01-13 21:54:31,103 - sentence_transformers.SentenceTransformer - INFO - Load pretrained SentenceTransformer: intfloat/e5-large-v2
2025-01-13 21:54:36,559 - py.warnings - WARNING - /home/destroy0p/AgnijBiswas/Publishability-of-Research/venv/lib/python3.12/site-packages/pathway/xpacks/llm/vector_store.py:218: UserWarning: `_metadata` column is not present in Table <pathway.Table schema={'data': typing.Any}>. Filtering will not work for this Table
  warnings.warn(

2025-01-13 21:54:36,620 - py.warnings - WARNING - /home/destroy0p/AgnijBiswas/Publishability-of-Research/venv/lib/python3.12/site-packages/pathway/internals/parse_graph.py:249: UserWarning: There are operators in the computation graph that haven't been used. Use pathway.run() (or similar) to run the computation involving these nodes.
  warnings.warn(

2025-01-13 21:56:11,568 - httpx - INFO - HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2025-01-13 21:56:13,509 - httpx - INFO - HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2025-01-13 21:56:15,148 - httpx - INFO - HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2025-01-13 21:56:17,152 - sentence_transformers.SentenceTransformer - INFO - Load pretrained SentenceTransformer: intfloat/e5-large-v2
2025-01-13 21:56:22,155 - py.warnings - WARNING - /home/destroy0p/AgnijBiswas/Publishability-of-Research/venv/lib/python3.12/site-packages/pathway/xpacks/llm/vector_store.py:218: UserWarning: `_metadata` column is not present in Table <pathway.Table schema={'data': typing.Any}>. Filtering will not work for this Table
  warnings.warn(

2025-01-13 21:56:22,223 - py.warnings - WARNING - /home/destroy0p/AgnijBiswas/Publishability-of-Research/venv/lib/python3.12/site-packages/beartype/_util/hint/pep/utilpeptest.py:311: BeartypeDecorHintPep585DeprecationWarning: PEP 484 type hint typing.Sequence[str] deprecated by PEP 585. This hint is scheduled for removal in the first Python version released after October 5th, 2025. To resolve this, import this hint from "beartype.typing" rather than "typing". For further commentary and alternatives, see also:
    https://beartype.readthedocs.io/en/latest/api_roar/#pep-585-deprecations
  warn(

2025-01-13 21:56:22,427 - pathway_engine.engine.dataflow - INFO - Preparing Pathway computation
2025-01-13 21:56:22,440 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-13 21:56:22,478 - googleapiclient.discovery_cache - INFO - file_cache is only supported with oauth2client<4.0.0
2025-01-13 21:56:22,499 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-13 21:56:22,510 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-13 21:56:22,512 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-13 21:56:22,520 - pathway_engine.connectors.monitoring - INFO - PythonReader-0: 0 entries (1 minibatch(es)) have been sent to the engine
2025-01-13 21:56:22,520 - pathway_engine.connectors.monitoring - INFO - PythonReader-1: 0 entries (1 minibatch(es)) have been sent to the engine
2025-01-13 21:56:22,520 - pathway_engine.connectors.monitoring - INFO - PythonReader-2: 0 entries (1 minibatch(es)) have been sent to the engine
2025-01-13 21:56:22,520 - pathway_engine.connectors.monitoring - INFO - PythonReader-3: 0 entries (1 minibatch(es)) have been sent to the engine
2025-01-13 21:56:23,455 - py.warnings - WARNING - /home/destroy0p/AgnijBiswas/Publishability-of-Research/venv/lib/python3.12/site-packages/pathway/io/gdrive/__init__.py:191: UserWarning: cannot fetch metadata of file with id 11m_cx50ZGVUP_oAiR7_qzXC_7jStGluX0, reason: File not found: 11m_cx50ZGVUP_oAiR7_qzXC_7jStGluX0.
  warnings.warn(

2025-01-13 21:58:02,158 - httpx - INFO - HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2025-01-13 21:58:03,899 - httpx - INFO - HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2025-01-13 21:58:05,535 - httpx - INFO - HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2025-01-13 21:58:07,724 - sentence_transformers.SentenceTransformer - INFO - Load pretrained SentenceTransformer: intfloat/e5-large-v2
2025-01-13 21:58:13,370 - py.warnings - WARNING - /home/destroy0p/AgnijBiswas/Publishability-of-Research/venv/lib/python3.12/site-packages/pathway/xpacks/llm/vector_store.py:218: UserWarning: `_metadata` column is not present in Table <pathway.Table schema={'data': typing.Any}>. Filtering will not work for this Table
  warnings.warn(

2025-01-13 21:58:13,437 - py.warnings - WARNING - /home/destroy0p/AgnijBiswas/Publishability-of-Research/venv/lib/python3.12/site-packages/beartype/_util/hint/pep/utilpeptest.py:311: BeartypeDecorHintPep585DeprecationWarning: PEP 484 type hint typing.Sequence[str] deprecated by PEP 585. This hint is scheduled for removal in the first Python version released after October 5th, 2025. To resolve this, import this hint from "beartype.typing" rather than "typing". For further commentary and alternatives, see also:
    https://beartype.readthedocs.io/en/latest/api_roar/#pep-585-deprecations
  warn(

2025-01-13 21:58:13,639 - pathway_engine.engine.dataflow - INFO - Preparing Pathway computation
2025-01-13 21:58:13,641 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-13 21:58:13,678 - googleapiclient.discovery_cache - INFO - file_cache is only supported with oauth2client<4.0.0
2025-01-13 21:58:13,694 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-13 21:58:13,710 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-13 21:58:13,712 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-13 21:58:13,715 - pathway_engine.connectors.monitoring - INFO - PythonReader-0: 0 entries (1 minibatch(es)) have been sent to the engine
2025-01-13 21:58:13,715 - pathway_engine.connectors.monitoring - INFO - PythonReader-1: 0 entries (1 minibatch(es)) have been sent to the engine
2025-01-13 21:58:13,715 - pathway_engine.connectors.monitoring - INFO - PythonReader-2: 0 entries (1 minibatch(es)) have been sent to the engine
2025-01-13 21:58:13,715 - pathway_engine.connectors.monitoring - INFO - PythonReader-3: 0 entries (1 minibatch(es)) have been sent to the engine
2025-01-13 21:58:14,583 - py.warnings - WARNING - /home/destroy0p/AgnijBiswas/Publishability-of-Research/venv/lib/python3.12/site-packages/pathway/io/gdrive/__init__.py:191: UserWarning: cannot fetch metadata of file with id 11m_cx50ZGVUP_oAiR7_qzXC_7jStGluX0, reason: File not found: 11m_cx50ZGVUP_oAiR7_qzXC_7jStGluX0.
  warnings.warn(

2025-01-13 21:58:33,624 - root - INFO - {"_type": "request_payload", "session_id": "uuid-478e1eda-8d06-4dbf-b2a0-701b47072b7f", "payload": {"query": "1. Is the paper's language clear and concise?", "k": 3}}
2025-01-13 21:58:33,643 - pathway_engine.connectors.monitoring - INFO - PythonReader-1: 1 entries (399 minibatch(es)) have been sent to the engine
2025-01-13 21:58:34,659 - root - INFO - {"_type": "http_access", "method": "POST", "scheme": "http", "scheme_with_forwarded": "http", "host": "127.0.0.1:8745", "route": "/v1/retrieve", "content_type": "application/json", "user_agent": "python-requests/2.32.3", "unix_timestamp": 1736785713, "remote": "127.0.0.1", "session_id": "uuid-478e1eda-8d06-4dbf-b2a0-701b47072b7f", "headers": [{"header": "Host", "value": "127.0.0.1:8745"}, {"header": "User-Agent", "value": "python-requests/2.32.3"}, {"header": "Accept-Encoding", "value": "gzip, deflate"}, {"header": "Accept", "value": "*/*"}, {"header": "Connection", "value": "keep-alive"}, {"header": "Content-Type", "value": "application/json"}, {"header": "Content-Length", "value": "66"}], "status": 200, "time_elapsed": "1.035"}
2025-01-13 21:58:34,660 - aiohttp.access - INFO - 127.0.0.1 [13/Jan/2025:21:58:33 +0530] "POST /v1/retrieve HTTP/1.1" 200 161 "-" "python-requests/2.32.3"
2025-01-13 21:58:34,882 - pathway_engine.engine.dataflow - INFO - Preparing Pathway computation
2025-01-13 21:58:34,914 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-13 21:58:34,915 - googleapiclient.discovery_cache - INFO - file_cache is only supported with oauth2client<4.0.0
2025-01-13 21:58:34,925 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-13 21:58:34,940 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-13 21:58:34,941 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-13 21:58:34,943 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-13 21:58:34,944 - pathway_engine.connectors - ERROR - There had been an error processing the row read result: OSError: [Errno 98] error while attempting to bind on address ('127.0.0.1', 8745): address already in use
2025-01-13 21:58:34,957 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-13 21:58:34,959 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-13 21:58:38,693 - pathway_engine.connectors.monitoring - INFO - PythonReader-1: 0 entries (101 minibatch(es)) have been sent to the engine
2025-01-13 21:58:54,841 - root - INFO - {"_type": "request_payload", "session_id": "uuid-beb9e675-ca60-41ee-8dc1-65a66ef8afb2", "payload": {"query": "2. Are the paper's arguments well-organized and logical?", "k": 3}}
2025-01-13 21:58:54,843 - pathway_engine.connectors.monitoring - INFO - PythonReader-1: 1 entries (323 minibatch(es)) have been sent to the engine
2025-01-13 21:58:55,646 - root - INFO - {"_type": "http_access", "method": "POST", "scheme": "http", "scheme_with_forwarded": "http", "host": "127.0.0.1:8745", "route": "/v1/retrieve", "content_type": "application/json", "user_agent": "python-requests/2.32.3", "unix_timestamp": 1736785734, "remote": "127.0.0.1", "session_id": "uuid-beb9e675-ca60-41ee-8dc1-65a66ef8afb2", "headers": [{"header": "Host", "value": "127.0.0.1:8745"}, {"header": "User-Agent", "value": "python-requests/2.32.3"}, {"header": "Accept-Encoding", "value": "gzip, deflate"}, {"header": "Accept", "value": "*/*"}, {"header": "Connection", "value": "keep-alive"}, {"header": "Content-Type", "value": "application/json"}, {"header": "Content-Length", "value": "77"}], "status": 200, "time_elapsed": "0.805"}
2025-01-13 21:58:55,646 - aiohttp.access - INFO - 127.0.0.1 [13/Jan/2025:21:58:54 +0530] "POST /v1/retrieve HTTP/1.1" 200 161 "-" "python-requests/2.32.3"
2025-01-13 21:58:55,876 - pathway_engine.engine.dataflow - INFO - Preparing Pathway computation
2025-01-13 21:58:55,877 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-13 21:58:55,911 - googleapiclient.discovery_cache - INFO - file_cache is only supported with oauth2client<4.0.0
2025-01-13 21:58:55,923 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-13 21:58:55,936 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-13 21:58:55,937 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-13 21:58:55,939 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-13 21:58:55,939 - pathway_engine.connectors - ERROR - There had been an error processing the row read result: OSError: [Errno 98] error while attempting to bind on address ('127.0.0.1', 8745): address already in use
2025-01-13 21:58:55,948 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-13 21:58:55,950 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-13 21:58:55,951 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-13 21:58:55,952 - pathway_engine.connectors - ERROR - There had been an error processing the row read result: OSError: [Errno 98] error while attempting to bind on address ('127.0.0.1', 8745): address already in use
2025-01-13 21:58:55,973 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-13 21:58:55,975 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-13 21:58:59,893 - pathway_engine.connectors.monitoring - INFO - PythonReader-1: 0 entries (101 minibatch(es)) have been sent to the engine
2025-01-13 21:59:15,816 - root - INFO - {"_type": "request_payload", "session_id": "uuid-30b1c5a8-f11d-456a-b245-c27711b298dd", "payload": {"query": "3. Does the paper provide sufficient evidence to support its claims?", "k": 3}}
2025-01-13 22:00:18,144 - httpx - INFO - HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2025-01-13 22:00:21,064 - httpx - INFO - HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2025-01-13 22:00:23,161 - httpx - INFO - HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2025-01-13 22:00:25,178 - sentence_transformers.SentenceTransformer - INFO - Load pretrained SentenceTransformer: intfloat/e5-large-v2
2025-01-13 22:00:30,880 - py.warnings - WARNING - /home/destroy0p/AgnijBiswas/Publishability-of-Research/venv/lib/python3.12/site-packages/pathway/xpacks/llm/vector_store.py:218: UserWarning: `_metadata` column is not present in Table <pathway.Table schema={'data': typing.Any}>. Filtering will not work for this Table
  warnings.warn(

2025-01-13 22:00:30,931 - py.warnings - WARNING - /home/destroy0p/AgnijBiswas/Publishability-of-Research/venv/lib/python3.12/site-packages/beartype/_util/hint/pep/utilpeptest.py:311: BeartypeDecorHintPep585DeprecationWarning: PEP 484 type hint typing.Sequence[str] deprecated by PEP 585. This hint is scheduled for removal in the first Python version released after October 5th, 2025. To resolve this, import this hint from "beartype.typing" rather than "typing". For further commentary and alternatives, see also:
    https://beartype.readthedocs.io/en/latest/api_roar/#pep-585-deprecations
  warn(

2025-01-13 22:00:31,125 - pathway_engine.engine.dataflow - INFO - Preparing Pathway computation
2025-01-13 22:00:31,128 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-13 22:00:31,173 - googleapiclient.discovery_cache - INFO - file_cache is only supported with oauth2client<4.0.0
2025-01-13 22:00:31,190 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-13 22:00:31,205 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-13 22:00:31,207 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-13 22:00:31,210 - pathway_engine.connectors.monitoring - INFO - PythonReader-0: 0 entries (1 minibatch(es)) have been sent to the engine
2025-01-13 22:00:31,210 - pathway_engine.connectors.monitoring - INFO - PythonReader-1: 0 entries (1 minibatch(es)) have been sent to the engine
2025-01-13 22:00:31,210 - pathway_engine.connectors.monitoring - INFO - PythonReader-2: 0 entries (1 minibatch(es)) have been sent to the engine
2025-01-13 22:00:31,210 - pathway_engine.connectors.monitoring - INFO - PythonReader-3: 0 entries (1 minibatch(es)) have been sent to the engine
2025-01-13 22:00:32,140 - py.warnings - WARNING - /home/destroy0p/AgnijBiswas/Publishability-of-Research/venv/lib/python3.12/site-packages/pathway/io/gdrive/__init__.py:191: UserWarning: cannot fetch metadata of file with id 11m_cx50ZGVUP_oAiR7_qzXC_7jStGluX0, reason: File not found: 11m_cx50ZGVUP_oAiR7_qzXC_7jStGluX0.
  warnings.warn(

2025-01-13 22:00:51,102 - root - INFO - {"_type": "request_payload", "session_id": "uuid-5239b543-40cf-456a-8c97-6f36ba712eea", "payload": {"query": "1. Is the paper's introduction clear and concise?", "k": 3}}
2025-01-13 22:00:51,139 - pathway_engine.connectors.monitoring - INFO - PythonReader-1: 1 entries (399 minibatch(es)) have been sent to the engine
2025-01-13 22:00:52,132 - root - INFO - {"_type": "http_access", "method": "POST", "scheme": "http", "scheme_with_forwarded": "http", "host": "127.0.0.1:8745", "route": "/v1/retrieve", "content_type": "application/json", "user_agent": "python-requests/2.32.3", "unix_timestamp": 1736785851, "remote": "127.0.0.1", "session_id": "uuid-5239b543-40cf-456a-8c97-6f36ba712eea", "headers": [{"header": "Host", "value": "127.0.0.1:8745"}, {"header": "User-Agent", "value": "python-requests/2.32.3"}, {"header": "Accept-Encoding", "value": "gzip, deflate"}, {"header": "Accept", "value": "*/*"}, {"header": "Connection", "value": "keep-alive"}, {"header": "Content-Type", "value": "application/json"}, {"header": "Content-Length", "value": "70"}], "status": 200, "time_elapsed": "1.030"}
2025-01-13 22:00:52,133 - aiohttp.access - INFO - 127.0.0.1 [13/Jan/2025:22:00:51 +0530] "POST /v1/retrieve HTTP/1.1" 200 161 "-" "python-requests/2.32.3"
2025-01-13 22:00:52,363 - pathway_engine.engine.dataflow - INFO - Preparing Pathway computation
2025-01-13 22:00:52,366 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-13 22:00:52,403 - googleapiclient.discovery_cache - INFO - file_cache is only supported with oauth2client<4.0.0
2025-01-13 22:00:52,414 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-13 22:00:52,424 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-13 22:00:52,426 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-13 22:00:52,428 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-13 22:00:52,429 - pathway_engine.connectors - ERROR - There had been an error processing the row read result: OSError: [Errno 98] error while attempting to bind on address ('127.0.0.1', 8745): address already in use
2025-01-13 22:00:52,443 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-13 22:00:52,446 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-13 22:00:56,139 - pathway_engine.connectors.monitoring - INFO - PythonReader-1: 0 entries (100 minibatch(es)) have been sent to the engine
2025-01-13 22:01:12,321 - root - INFO - {"_type": "request_payload", "session_id": "uuid-8e328b7c-b502-4d01-bfee-d3ef6ff9a389", "payload": {"query": "2. Are the research objectives and methodology well-defined?", "k": 3}}
2025-01-13 22:01:12,339 - pathway_engine.connectors.monitoring - INFO - PythonReader-1: 1 entries (324 minibatch(es)) have been sent to the engine
2025-01-13 22:01:13,136 - root - INFO - {"_type": "http_access", "method": "POST", "scheme": "http", "scheme_with_forwarded": "http", "host": "127.0.0.1:8745", "route": "/v1/retrieve", "content_type": "application/json", "user_agent": "python-requests/2.32.3", "unix_timestamp": 1736785872, "remote": "127.0.0.1", "session_id": "uuid-8e328b7c-b502-4d01-bfee-d3ef6ff9a389", "headers": [{"header": "Host", "value": "127.0.0.1:8745"}, {"header": "User-Agent", "value": "python-requests/2.32.3"}, {"header": "Accept-Encoding", "value": "gzip, deflate"}, {"header": "Accept", "value": "*/*"}, {"header": "Connection", "value": "keep-alive"}, {"header": "Content-Type", "value": "application/json"}, {"header": "Content-Length", "value": "81"}], "status": 200, "time_elapsed": "0.816"}
2025-01-13 22:01:13,136 - aiohttp.access - INFO - 127.0.0.1 [13/Jan/2025:22:01:12 +0530] "POST /v1/retrieve HTTP/1.1" 200 161 "-" "python-requests/2.32.3"
2025-01-13 22:01:13,392 - pathway_engine.engine.dataflow - INFO - Preparing Pathway computation
2025-01-13 22:01:13,393 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-13 22:01:13,426 - googleapiclient.discovery_cache - INFO - file_cache is only supported with oauth2client<4.0.0
2025-01-13 22:01:13,444 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-13 22:01:13,458 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-13 22:01:13,461 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-13 22:01:13,462 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-13 22:01:13,462 - pathway_engine.connectors - ERROR - There had been an error processing the row read result: OSError: [Errno 98] error while attempting to bind on address ('127.0.0.1', 8745): address already in use
2025-01-13 22:01:13,472 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-13 22:01:13,474 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-13 22:01:13,475 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-13 22:01:13,477 - pathway_engine.connectors - ERROR - There had been an error processing the row read result: OSError: [Errno 98] error while attempting to bind on address ('127.0.0.1', 8745): address already in use
2025-01-13 22:01:13,492 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-13 22:01:13,495 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-13 22:01:17,339 - pathway_engine.connectors.monitoring - INFO - PythonReader-1: 0 entries (100 minibatch(es)) have been sent to the engine
2025-01-13 22:01:33,321 - root - INFO - {"_type": "request_payload", "session_id": "uuid-4412c98e-2c24-403c-8b17-54d7689ac59e", "payload": {"query": "3. Is the literature review relevant and up-to-date?", "k": 3}}
2025-01-13 22:03:50,043 - aiohttp.access - INFO - 127.0.0.1 [13/Jan/2025:22:03:50 +0530] "GET / HTTP/1.1" 404 175 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36"
2025-01-13 22:03:50,087 - aiohttp.access - INFO - 127.0.0.1 [13/Jan/2025:22:03:50 +0530] "GET /favicon.ico HTTP/1.1" 404 175 "http://127.0.0.1:8745/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36"
2025-01-13 22:05:43,471 - httpx - INFO - HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2025-01-13 22:05:45,214 - httpx - INFO - HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2025-01-13 22:05:47,054 - httpx - INFO - HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2025-01-13 22:05:48,964 - sentence_transformers.SentenceTransformer - INFO - Load pretrained SentenceTransformer: intfloat/e5-large-v2
2025-01-13 22:05:54,217 - py.warnings - WARNING - /home/destroy0p/AgnijBiswas/Publishability-of-Research/venv/lib/python3.12/site-packages/pathway/xpacks/llm/vector_store.py:218: UserWarning: `_metadata` column is not present in Table <pathway.Table schema={'data': typing.Any}>. Filtering will not work for this Table
  warnings.warn(

2025-01-13 22:05:54,271 - py.warnings - WARNING - /home/destroy0p/AgnijBiswas/Publishability-of-Research/venv/lib/python3.12/site-packages/beartype/_util/hint/pep/utilpeptest.py:311: BeartypeDecorHintPep585DeprecationWarning: PEP 484 type hint typing.Sequence[str] deprecated by PEP 585. This hint is scheduled for removal in the first Python version released after October 5th, 2025. To resolve this, import this hint from "beartype.typing" rather than "typing". For further commentary and alternatives, see also:
    https://beartype.readthedocs.io/en/latest/api_roar/#pep-585-deprecations
  warn(

2025-01-13 22:05:54,473 - pathway_engine.engine.dataflow - INFO - Preparing Pathway computation
2025-01-13 22:05:54,475 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-13 22:05:54,513 - googleapiclient.discovery_cache - INFO - file_cache is only supported with oauth2client<4.0.0
2025-01-13 22:05:54,523 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-13 22:05:54,535 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-13 22:05:54,537 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-13 22:05:54,541 - pathway_engine.connectors.monitoring - INFO - PythonReader-0: 0 entries (1 minibatch(es)) have been sent to the engine
2025-01-13 22:05:54,541 - pathway_engine.connectors.monitoring - INFO - PythonReader-1: 0 entries (1 minibatch(es)) have been sent to the engine
2025-01-13 22:05:54,541 - pathway_engine.connectors.monitoring - INFO - PythonReader-2: 0 entries (1 minibatch(es)) have been sent to the engine
2025-01-13 22:05:54,541 - pathway_engine.connectors.monitoring - INFO - PythonReader-3: 0 entries (1 minibatch(es)) have been sent to the engine
2025-01-13 22:05:55,488 - py.warnings - WARNING - /home/destroy0p/AgnijBiswas/Publishability-of-Research/venv/lib/python3.12/site-packages/pathway/io/gdrive/__init__.py:191: UserWarning: cannot fetch metadata of file with id 11m_cx50ZGVUP_oAiR7_qzXC_7jStGluX0, reason: File not found: 11m_cx50ZGVUP_oAiR7_qzXC_7jStGluX0.
  warnings.warn(

2025-01-13 22:06:14,448 - root - INFO - {"_type": "request_payload", "session_id": "uuid-94f64ba7-c56e-4994-bc6b-281eedf93865", "payload": {"query": "1. Is the paper's grammar and punctuation correct?", "k": 3}}
2025-01-13 22:06:14,473 - pathway_engine.connectors.monitoring - INFO - PythonReader-1: 1 entries (399 minibatch(es)) have been sent to the engine
2025-01-13 22:06:15,480 - root - INFO - {"_type": "http_access", "method": "POST", "scheme": "http", "scheme_with_forwarded": "http", "host": "127.0.0.1:8745", "route": "/v1/retrieve", "content_type": "application/json", "user_agent": "python-requests/2.32.3", "unix_timestamp": 1736786174, "remote": "127.0.0.1", "session_id": "uuid-94f64ba7-c56e-4994-bc6b-281eedf93865", "headers": [{"header": "Host", "value": "127.0.0.1:8745"}, {"header": "User-Agent", "value": "python-requests/2.32.3"}, {"header": "Accept-Encoding", "value": "gzip, deflate"}, {"header": "Accept", "value": "*/*"}, {"header": "Connection", "value": "keep-alive"}, {"header": "Content-Type", "value": "application/json"}, {"header": "Content-Length", "value": "71"}], "status": 200, "time_elapsed": "1.032"}
2025-01-13 22:06:15,480 - aiohttp.access - INFO - 127.0.0.1 [13/Jan/2025:22:06:14 +0530] "POST /v1/retrieve HTTP/1.1" 200 161 "-" "python-requests/2.32.3"
2025-01-13 22:06:15,710 - pathway_engine.engine.dataflow - INFO - Preparing Pathway computation
2025-01-13 22:06:15,711 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-13 22:06:15,750 - googleapiclient.discovery_cache - INFO - file_cache is only supported with oauth2client<4.0.0
2025-01-13 22:06:15,758 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-13 22:06:15,768 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-13 22:06:15,770 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-13 22:06:15,771 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-13 22:06:15,773 - pathway_engine.connectors - ERROR - There had been an error processing the row read result: OSError: [Errno 98] error while attempting to bind on address ('127.0.0.1', 8745): address already in use
2025-01-13 22:06:15,785 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-13 22:06:15,787 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-13 22:06:19,473 - pathway_engine.connectors.monitoring - INFO - PythonReader-1: 0 entries (100 minibatch(es)) have been sent to the engine
2025-01-13 22:06:35,669 - root - INFO - {"_type": "request_payload", "session_id": "uuid-2e824fa4-7b71-4420-a64d-e772b9ac144b", "payload": {"query": "2. Is the paper's structure and organization logical and easy to follow?", "k": 3}}
2025-01-13 22:06:35,673 - pathway_engine.connectors.monitoring - INFO - PythonReader-1: 1 entries (324 minibatch(es)) have been sent to the engine
2025-01-13 22:06:36,480 - root - INFO - {"_type": "http_access", "method": "POST", "scheme": "http", "scheme_with_forwarded": "http", "host": "127.0.0.1:8745", "route": "/v1/retrieve", "content_type": "application/json", "user_agent": "python-requests/2.32.3", "unix_timestamp": 1736786195, "remote": "127.0.0.1", "session_id": "uuid-2e824fa4-7b71-4420-a64d-e772b9ac144b", "headers": [{"header": "Host", "value": "127.0.0.1:8745"}, {"header": "User-Agent", "value": "python-requests/2.32.3"}, {"header": "Accept-Encoding", "value": "gzip, deflate"}, {"header": "Accept", "value": "*/*"}, {"header": "Connection", "value": "keep-alive"}, {"header": "Content-Type", "value": "application/json"}, {"header": "Content-Length", "value": "93"}], "status": 200, "time_elapsed": "0.811"}
2025-01-13 22:06:36,480 - aiohttp.access - INFO - 127.0.0.1 [13/Jan/2025:22:06:35 +0530] "POST /v1/retrieve HTTP/1.1" 200 161 "-" "python-requests/2.32.3"
2025-01-13 22:06:36,732 - pathway_engine.engine.dataflow - INFO - Preparing Pathway computation
2025-01-13 22:06:36,735 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-13 22:06:36,784 - googleapiclient.discovery_cache - INFO - file_cache is only supported with oauth2client<4.0.0
2025-01-13 22:06:36,793 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-13 22:06:36,803 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-13 22:06:36,804 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-13 22:06:36,807 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-13 22:06:36,807 - pathway_engine.connectors - ERROR - There had been an error processing the row read result: OSError: [Errno 98] error while attempting to bind on address ('127.0.0.1', 8745): address already in use
2025-01-13 22:06:36,823 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-13 22:06:36,825 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-13 22:06:36,826 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-13 22:06:36,827 - pathway_engine.connectors - ERROR - There had been an error processing the row read result: OSError: [Errno 98] error while attempting to bind on address ('127.0.0.1', 8745): address already in use
2025-01-13 22:06:36,842 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-13 22:06:36,844 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-13 22:06:40,673 - pathway_engine.connectors.monitoring - INFO - PythonReader-1: 0 entries (100 minibatch(es)) have been sent to the engine
2025-01-13 22:06:56,659 - root - INFO - {"_type": "request_payload", "session_id": "uuid-268dd7b6-3c30-479b-8652-aa04d1256a90", "payload": {"query": "3. Are the paper's arguments and claims well-supported by evidence and examples?", "k": 3}}
2025-01-13 22:08:41,853 - httpx - INFO - HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2025-01-13 22:08:43,593 - httpx - INFO - HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2025-01-13 22:08:44,821 - httpx - INFO - HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2025-01-13 22:08:46,740 - sentence_transformers.SentenceTransformer - INFO - Load pretrained SentenceTransformer: intfloat/e5-large-v2
2025-01-13 22:09:01,372 - py.warnings - WARNING - /home/destroy0p/AgnijBiswas/Publishability-of-Research/venv/lib/python3.12/site-packages/pathway/xpacks/llm/vector_store.py:218: UserWarning: `_metadata` column is not present in Table <pathway.Table schema={'data': typing.Any}>. Filtering will not work for this Table
  warnings.warn(

2025-01-13 22:09:01,433 - py.warnings - WARNING - /home/destroy0p/AgnijBiswas/Publishability-of-Research/venv/lib/python3.12/site-packages/beartype/_util/hint/pep/utilpeptest.py:311: BeartypeDecorHintPep585DeprecationWarning: PEP 484 type hint typing.Sequence[str] deprecated by PEP 585. This hint is scheduled for removal in the first Python version released after October 5th, 2025. To resolve this, import this hint from "beartype.typing" rather than "typing". For further commentary and alternatives, see also:
    https://beartype.readthedocs.io/en/latest/api_roar/#pep-585-deprecations
  warn(

2025-01-13 22:09:01,628 - pathway_engine.engine.dataflow - INFO - Preparing Pathway computation
2025-01-13 22:09:01,628 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-13 22:09:01,661 - googleapiclient.discovery_cache - INFO - file_cache is only supported with oauth2client<4.0.0
2025-01-13 22:09:01,672 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-13 22:09:01,693 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-13 22:09:01,694 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-13 22:09:01,698 - pathway_engine.connectors.monitoring - INFO - PythonReader-0: 0 entries (1 minibatch(es)) have been sent to the engine
2025-01-13 22:09:01,698 - pathway_engine.connectors.monitoring - INFO - PythonReader-1: 0 entries (1 minibatch(es)) have been sent to the engine
2025-01-13 22:09:01,698 - pathway_engine.connectors.monitoring - INFO - PythonReader-2: 0 entries (1 minibatch(es)) have been sent to the engine
2025-01-13 22:09:01,698 - pathway_engine.connectors.monitoring - INFO - PythonReader-3: 0 entries (1 minibatch(es)) have been sent to the engine
2025-01-13 22:09:02,587 - py.warnings - WARNING - /home/destroy0p/AgnijBiswas/Publishability-of-Research/venv/lib/python3.12/site-packages/pathway/io/gdrive/__init__.py:191: UserWarning: cannot fetch metadata of file with id 11m_cx50ZGVUP_oAiR7_qzXC_7jStGluX0, reason: File not found: 11m_cx50ZGVUP_oAiR7_qzXC_7jStGluX0.
  warnings.warn(

2025-01-13 22:09:21,601 - root - INFO - {"_type": "request_payload", "session_id": "uuid-2a79d11b-2b3e-4593-8345-a2958f7f3d4c", "payload": {"query": "1. Is the paper free of grammatical errors?", "k": 3}}
2025-01-13 22:09:21,621 - pathway_engine.connectors.monitoring - INFO - PythonReader-1: 1 entries (399 minibatch(es)) have been sent to the engine
2025-01-13 22:09:22,634 - root - INFO - {"_type": "http_access", "method": "POST", "scheme": "http", "scheme_with_forwarded": "http", "host": "127.0.0.1:8745", "route": "/v1/retrieve", "content_type": "application/json", "user_agent": "python-requests/2.32.3", "unix_timestamp": 1736786361, "remote": "127.0.0.1", "session_id": "uuid-2a79d11b-2b3e-4593-8345-a2958f7f3d4c", "headers": [{"header": "Host", "value": "127.0.0.1:8745"}, {"header": "User-Agent", "value": "python-requests/2.32.3"}, {"header": "Accept-Encoding", "value": "gzip, deflate"}, {"header": "Accept", "value": "*/*"}, {"header": "Connection", "value": "keep-alive"}, {"header": "Content-Type", "value": "application/json"}, {"header": "Content-Length", "value": "64"}], "status": 200, "time_elapsed": "1.033"}
2025-01-13 22:09:22,640 - aiohttp.access - INFO - 127.0.0.1 [13/Jan/2025:22:09:21 +0530] "POST /v1/retrieve HTTP/1.1" 200 161 "-" "python-requests/2.32.3"
2025-01-13 22:09:22,859 - pathway_engine.engine.dataflow - INFO - Preparing Pathway computation
2025-01-13 22:09:22,860 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-13 22:09:22,891 - googleapiclient.discovery_cache - INFO - file_cache is only supported with oauth2client<4.0.0
2025-01-13 22:09:22,901 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-13 22:09:22,912 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-13 22:09:22,913 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-13 22:09:22,915 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-13 22:09:22,917 - pathway_engine.connectors - ERROR - There had been an error processing the row read result: OSError: [Errno 98] error while attempting to bind on address ('127.0.0.1', 8745): address already in use
2025-01-13 22:09:22,930 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-13 22:09:22,932 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-13 22:09:26,671 - pathway_engine.connectors.monitoring - INFO - PythonReader-1: 0 entries (101 minibatch(es)) have been sent to the engine
2025-01-13 22:09:42,818 - root - INFO - {"_type": "request_payload", "session_id": "uuid-e8a80fa0-7481-4dea-9fb8-e4eab202e6d9", "payload": {"query": "2. Is the paper well-structured and easy to follow?", "k": 3}}
2025-01-13 22:09:42,821 - pathway_engine.connectors.monitoring - INFO - PythonReader-1: 1 entries (323 minibatch(es)) have been sent to the engine
2025-01-13 22:09:43,635 - root - INFO - {"_type": "http_access", "method": "POST", "scheme": "http", "scheme_with_forwarded": "http", "host": "127.0.0.1:8745", "route": "/v1/retrieve", "content_type": "application/json", "user_agent": "python-requests/2.32.3", "unix_timestamp": 1736786382, "remote": "127.0.0.1", "session_id": "uuid-e8a80fa0-7481-4dea-9fb8-e4eab202e6d9", "headers": [{"header": "Host", "value": "127.0.0.1:8745"}, {"header": "User-Agent", "value": "python-requests/2.32.3"}, {"header": "Accept-Encoding", "value": "gzip, deflate"}, {"header": "Accept", "value": "*/*"}, {"header": "Connection", "value": "keep-alive"}, {"header": "Content-Type", "value": "application/json"}, {"header": "Content-Length", "value": "72"}], "status": 200, "time_elapsed": "0.816"}
2025-01-13 22:09:43,643 - aiohttp.access - INFO - 127.0.0.1 [13/Jan/2025:22:09:42 +0530] "POST /v1/retrieve HTTP/1.1" 200 161 "-" "python-requests/2.32.3"
2025-01-13 22:09:43,908 - pathway_engine.engine.dataflow - INFO - Preparing Pathway computation
2025-01-13 22:09:43,910 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-13 22:09:43,945 - googleapiclient.discovery_cache - INFO - file_cache is only supported with oauth2client<4.0.0
2025-01-13 22:09:43,954 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-13 22:09:43,964 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-13 22:09:43,967 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-13 22:09:43,969 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-13 22:09:43,969 - pathway_engine.connectors - ERROR - There had been an error processing the row read result: OSError: [Errno 98] error while attempting to bind on address ('127.0.0.1', 8745): address already in use
2025-01-13 22:09:43,980 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-13 22:09:43,982 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-13 22:09:43,985 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-13 22:09:43,986 - pathway_engine.connectors - ERROR - There had been an error processing the row read result: OSError: [Errno 98] error while attempting to bind on address ('127.0.0.1', 8745): address already in use
2025-01-13 22:09:44,005 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-13 22:09:44,008 - pathway_engine.connectors - INFO - Enter read_snapshot method with reader Python
2025-01-13 22:09:47,871 - pathway_engine.connectors.monitoring - INFO - PythonReader-1: 0 entries (101 minibatch(es)) have been sent to the engine
2025-01-13 22:10:03,840 - root - INFO - {"_type": "request_payload", "session_id": "uuid-2028c4d7-28f1-44a7-bed9-6a971be43fda", "payload": {"query": "3. Are the arguments and claims in the paper well-supported by evidence?", "k": 3}}
